name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    name: Flow CLI Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Install Flow CLI
      run: sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v1.8.0
    - name: Run tests
      run: make ci
    - name: Normalize coverage report filepaths
      run : sh ./normalize_coverage_report.sh
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
 